services:
  - type: web
    name: shadowcore
    env: node
    region: singapore
    plan: free
    buildCommand: |
      npm install
      npm run setup
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: OWNER_NAME
        value: Abdullah
      - key: OWNER_CONTACT
        value: "+923288055104"
      - key: ADMIN_PASSWORD
        value: Rana0986
      - key: REMOVEBG_API_KEY
        value: xv5aoeuirxTNZBYS5KykZZEK

databases:
  - name: shadowcore-db
    plan: free
    databaseName: shadowcore
    user: shadowcore_user
